### ISSUE TITLE
Documentation source links don't work

### ISSUE THREAD

**Issue by parkersruth** [vispy/vispy-website#22]
Clicking the [source] links to the right of the methods in the documentation leads to the GitHUB 404 page not found error. E.g. consider [this page](http://vispy.org/vispy.html).

**Comment by djhoese** [comment]
Ah thanks for letting us know. It looks like this is a mistake on this line of code: https://github.com/vispy/vispy-website/blob/master/conf.py#L416

It should probably use `v0.5.0` instead of `0.5` since that is what the git tags are. I will try to get to this when I have a chance but if you @parkersruth have a moment it shouldn't be too hard to fix.
